apiVersion: v1
kind: Service
metadata:
  name: assist
spec:
  selector:
    app: assist
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assist
spec:
  selector:
    matchLabels:
      app: assist
  template:
    metadata:
      labels:
        app: assist
    spec:
      containers:
        - name: assist
          image: {{.Values.imageAssist | quote}}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: "DATABASE_URL"
              value: {{.Values.assist.databaseUrl}}
          startupProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: 4000
            initialDelaySeconds: 200
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
