version: '3.8'

services:
  mysql:
    image: bitnami/mysql
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/bitnami/mysql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_USER=assist
      - MYSQL_ROOT_PASSWORD=assist
      - MYSQL_DATABASE=assist
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mysql:
